// TAU — frontend
// Cole a URL /exec do Web App do Apps Script aqui.
const API_URL='https://script.google.com/macros/s/AKfycbw8B-2E5NOl87Y5cUYxJ2_d0A1dgO5slPFN6X41LetXkE5zIGxowkyLgGZAz9dsXHuP/exec';
let S={token:localStorage.getItem('tau_token')||'',user:null,subjects:[],notes:[],important:[],reminders:[],questions:[],materials:[]};

const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2500)}
function api(action,data={}){return fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,token:S.token,...data})}).then(r=>r.json())}
async function call(action,data={}){const r=await api(action,data);if(!r.ok)throw Error(r.message||'Não foi possível concluir.');return r.data}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page))}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));

async function start(){try{const d=await call('bootstrap');Object.assign(S,d);$('login').classList.add('hidden');$('app').classList.remove('hidden');$('userName').textContent=S.user.NOME;$('avatar').textContent=(S.user.NOME||'T')[0].toUpperCase();render()}catch(e){localStorage.removeItem('tau_token');S.token='';toast(e.message)}}
function render(){renderStats();renderSubjects();renderRecent();renderReminders();renderQuestions();renderMaterials();renderImportant();renderReview()}
function renderStats(){$('nSubjects').textContent=S.subjects.length;$('nNotes').textContent=S.notes.length;$('nImportant').textContent=S.important.length;$('nReminders').textContent=S.reminders.length}
function subjectName(id){return S.subjects.find(x=>x.MATERIA_ID===id)?.NOME||'Sem matéria'}
function renderSubjects(){$('subjectsList').innerHTML=S.subjects.length?S.subjects.map(s=>`<div class="card" onclick="detail('${s.MATERIA_ID}')"><span class="dot"></span><small>Matéria</small><h3>${esc(s.NOME)}</h3><small>${S.notes.filter(n=>n.MATERIA_ID===s.MATERIA_ID).length} anotações</small></div>`).join(''):'<div class="empty">Crie sua primeira matéria.</div>'}
function renderRecent(){const a=S.notes.slice(-6).reverse();$('recent').innerHTML=a.length?a.map(n=>`<div class="card"><small>${esc(subjectName(n.MATERIA_ID))}</small><h3>${esc(n.TITULO)}</h3><p class="muted">${esc((n.CONTEUDO||'').slice(0,100))}</p></div>`).join(''):'<div class="empty">Suas anotações recentes aparecerão aqui.</div>'}
function renderReminders(){const a=[...S.reminders].sort((x,y)=>(x.DATA+x.HORA).localeCompare(y.DATA+y.HORA));$('remindersList').innerHTML=a.length?a.map(r=>`<div class="card"><h3>${esc(r.TITULO)}</h3><small>${esc(r.DATA)} às ${esc(r.HORA)}</small><p>${esc(r.DESCRICAO)}</p></div>`).join(''):'<div class="empty">Nenhum lembrete.</div>';$('nextReminders').innerHTML=a.slice(0,3).map(r=>`<div class="card"><b>${esc(r.TITULO)}</b><p class="muted">${esc(r.DATA)} às ${esc(r.HORA)}</p></div>`).join('')||'<div class="empty">Nenhum lembrete próximo.</div>'}
function renderQuestions(){$('questionsList').innerHTML=S.questions.map(q=>`<div class="card"><small>${esc(q.CATEGORIA)}</small><h3>${esc(q.PERGUNTA)}</h3><button class="secondary" onclick="navigator.clipboard?.writeText(${JSON.stringify(q.PERGUNTA)});toast('Pergunta copiada')">Usar pergunta</button></div>`).join('')}
function renderMaterials(){$('materialsList').innerHTML=S.materials.length?S.materials.map(m=>`<div class="card"><small>${esc(m.TIPO)}</small><h3>${esc(m.NOME)}</h3></div>`).join(''):'<div class="empty">Nenhum material salvo.</div>'}
function renderImportant(){ $('importantList').innerHTML=S.important.length?S.important.map(i=>{const n=S.notes.find(x=>x.ANOTACAO_ID===i.ANOTACAO_ID);return `<div class="important"><b>${esc(n?.TITULO||'Anotação')}</b><p><span class="highlight">${esc(i.TEXTO_MARCADO)}</span></p><small>${esc(subjectName(n?.MATERIA_ID))}</small></div>`}).join(''):'<div class="empty">Nenhum trecho marcado.</div>'}
function renderReview(){$('reviewList').innerHTML=`<div class="cards"><div class="card"><b>${S.important.length}</b><p class="muted">trechos importantes</p></div><div class="card"><b>${S.notes.length}</b><p class="muted">anotações</p></div></div><div class="section">${S.important.slice(0,10).map(i=>`<div class="important">${esc(i.TEXTO_MARCADO)}</div>`).join('')||'<div class="empty">Marque trechos para revisar depois.</div>'}</div>`}

function modal(title,body,save){$('modalBox').innerHTML=`<div class="modal-head"><h2>${title}</h2><button class="close" onclick="closeModal()">×</button></div><form id="modalForm" class="form">${body}<div class="actions"><button type="button" class="secondary" onclick="closeModal()">Cancelar</button><button class="primary">Salvar</button></div></form>`;$('modal').classList.add('show');$('modalForm').onsubmit=async e=>{e.preventDefault();try{await save();closeModal();await start()}catch(x){toast(x.message)}}}
function closeModal(){$('modal').classList.remove('show')}
function register(){modal('Criar conta',`<input id="rName" placeholder="Nome" required><input id="rEmail" type="email" placeholder="E-mail" required><input id="rPass" type="password" minlength="6" placeholder="Senha" required>`,async()=>{const d=await call('register',{name:$('rName').value,email:$('rEmail').value,password:$('rPass').value});S.token=d.token;localStorage.setItem('tau_token',S.token)})}
$('openRegister').onclick=register;
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await call('login',{email:$('email').value,password:$('password').value});S.token=d.token;localStorage.setItem('tau_token',S.token);start()}catch(x){toast(x.message)}};

function newSubject(){modal('Nova matéria',`<input id="subjectName" placeholder="Nome da matéria" required>`,async()=>call('createSubject',{name:$('subjectName').value}))}
$('newSubject').onclick=newSubject;
function newReminder(){modal('Novo lembrete',`<input id="rt" placeholder="Título" required><input id="rd" type="date" required><input id="rh" type="time" required><textarea id="rx" placeholder="Observação"></textarea>`,async()=>call('createReminder',{title:$('rt').value,date:$('rd').value,time:$('rh').value,description:$('rx').value}))}
$('newReminder').onclick=newReminder;
function newMaterial(){modal('Adicionar material',`<input id="mn" placeholder="Nome do material" required><select id="ms">${S.subjects.map(s=>`<option value="${s.MATERIA_ID}">${esc(s.NOME)}</option>`).join('')}</select><input id="mf" type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,image/*">`,async()=>toast('A rotina de upload precisa ser ligada ao Drive no Apps Script.'))}
$('newMaterial').onclick=newMaterial;
function detail(id){const s=S.subjects.find(x=>x.MATERIA_ID===id),notes=S.notes.filter(n=>n.MATERIA_ID===id);$('subjectDetail').innerHTML=`<button class="link" onclick="show('subjects')">← Voltar</button><h1>${esc(s.NOME)}</h1><div class="tabs"><button class="active">Anotações</button><button>Materiais</button><button>Importantes</button><button>Revisar</button></div><button class="primary" onclick="newNote('${id}')">+ Nova anotação</button>${notes.length?notes.map(n=>`<article class="note"><h3>${esc(n.TITULO)}</h3><p>${esc(n.CONTEUDO).replace(/\n/g,'<br>')}</p><button class="primary" style="background:var(--yellow);color:var(--text)" onclick="highlight('${n.ANOTACAO_ID}')">Marca-texto</button></article>`).join(''):'<div class="empty" style="margin-top:15px">Nenhuma anotação.</div>'}`;show('subjectDetail')}
function newNote(subjectId){modal('Nova anotação',`<select id="ns">${S.subjects.map(s=>`<option value="${s.MATERIA_ID}" ${s.MATERIA_ID===subjectId?'selected':''}>${esc(s.NOME)}</option>`).join('')}</select><input id="nt" placeholder="Título" required><textarea id="nc" placeholder="Escreva sua anotação..."></textarea>`,async()=>call('createNote',{subjectId:$('ns').value,title:$('nt').value,content:$('nc').value}))}
function highlight(noteId){const n=S.notes.find(x=>x.ANOTACAO_ID===noteId);const text=prompt('Cole ou digite o trecho que deseja marcar:',n?.CONTEUDO||'');if(text)call('addHighlight',{noteId,text}).then(start).catch(e=>toast(e.message))}
$('quick').onclick=()=>modal('Adicionar ao TAU',`<button type="button" class="secondary" onclick="closeModal();newNote(S.subjects[0]?.MATERIA_ID)">📝 Nova anotação</button><button type="button" class="secondary" onclick="closeModal();newMaterial()">📎 Material</button><button type="button" class="secondary" onclick="closeModal();newReminder()">◷ Lembrete</button>`,async()=>{});

$('search').oninput=e=>{const q=e.target.value.toLowerCase();if(!q){render();return}const a=S.notes.filter(n=>(n.TITULO+' '+n.CONTEUDO+' '+subjectName(n.MATERIA_ID)).toLowerCase().includes(q));$('recent').innerHTML=a.map(n=>`<div class="card"><small>${esc(subjectName(n.MATERIA_ID))}</small><h3>${esc(n.TITULO)}</h3><p>${esc(n.CONTEUDO)}</p></div>`).join('')||'<div class="empty">Nenhum resultado.</div>';show('home')};

if(S.token)start();
